version: '2'

services:
  tng-cat:
    #image: sonatanfv/tng-cat:dev
    #links:
    #  - mongo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4011:4011"
    restart: always
    environment:
      - MAIN_DB=tng-cat
      - MAIN_DB_HOST=localhost:27017
      #- SECOND_DB=tng-cat
      #- SECOND_DB_HOST=localhost:27017
    container_name: tng-cat

tng-cat_doc:
  image: sonatanfv/tng-cat:dev
  ports:
    - "8808:8808"
  command: [rake,yard]
  command: [yard, server, -B, 0.0.0.0]
  restart: always

mongodata:
  image: mongo:3.0.4
  volumes:
    - /data/db
  command: --break-mongo

mongo:
  image: mongo:3.0.4
  volumes_from:
    - mongodata
  ports:
    - "27017"
  command: --smallfiles --rest
  restart: always

mongoexpress:
  image: mongo-express
  links:
    - mongo:mongo
  ports:
    - "8081:8081"
  restart: always
